resolver: lts-10.4
packages:
  - katip
  - katip-elasticsearch
extra-deps:
  - unagi-chan-0.4.0.0
  # These can be dropped probably as soon as they hit an LTS
  - bloodhound-0.15.0.2
  - http-types-0.12
  - unliftio-core-0.1.1.0
flags:
  katip:
    lib-Werror: true
  katip-elasticsearch:
    lib-Werror: true
