resolver: lts-12.26
packages:
  - katip
  - katip-elasticsearch
  - katip-datadog
  - katip-logzio
extra-deps:
  - bloodhound-0.16.0.0
  - unliftio-core-0.1.2.0
  - unix-2.7.2.2
flags:
  katip:
    lib-Werror: true
  katip-elasticsearch:
    lib-Werror: true
  katip-datadog:
    lib-Werror: true
  katip-logzio:
    lib-Werror: true
