resolver: lts-12.22
packages:
  - katip
  - katip-elasticsearch
  - katip-datadog
extra-deps:
  - bloodhound-0.16.0.0
  - unliftio-core-0.1.2.0
flags:
  katip:
    lib-Werror: true
  katip-elasticsearch:
    lib-Werror: true
  katip-datadog:
    lib-Werror: true
