name: katip-elasticsearch
version: '0.4.0.1'
synopsis: ElasticSearch scribe for the Katip logging framework.
description: See README.md for more details.
category: Data
author: Ozgun Ataman, Michael Xavier
maintainer: michael.xavier@soostone.com
copyright: Soostone Inc 2015-2017
license: BSD3
tested-with: GHC==7.8.4 GHC==7.10.3
extra-source-files:
- README.md
- changelog.md
- bench/Main.hs
- examples/example.hs
- test/Main.hs

github: Soostone/katip

library:
  source-dirs:
  - src
  exposed-modules:
  - Katip.Scribes.ElasticSearch
  - Katip.Scribes.ElasticSearch.Annotations
  - Katip.Scribes.ElasticSearch.Internal
  dependencies:
  - base >=4.6 && <5
  - katip >=0.2.0.0 && <0.6
  - aeson >=0.6 && <1.3
  - async >=2.0.1.0 && <2.2
  - bloodhound >=0.13.0.0 && <0.16
  - bytestring
  - enclosed-exceptions >=1.0.0 && <1.1
  - exceptions
  - http-client >=0.3 && <0.6
  - http-types >=0.8 && <0.10
  - random >=1.1 && <1.2
  - retry >=0.7 && <0.8
  - scientific >=0.3.0.0 && <0.4
  - stm >=2.4.3 && <2.5
  - stm-chans >=3.0.0.2 && <3.1
  - text >=0.11 && <1.3
  - time >=1 && <1.9
  - transformers >=0.2 && <0.6
  - unagi-chan
  - unordered-containers >=0.1.0.0 && <0.3
  - uuid >=1.3.12 && <1.4
  - vector >= 0.12.0.1 && < 0.13.0.0
  when:
  - condition: flag(lib-werror)
    ghc-options:
    - -Wall
    - -Werror

tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - katip-elasticsearch
    - katip
    - http-client
    - bloodhound
    - base
    - tasty >=0.11
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-instances
    - containers
    - transformers
    - lens
    - lens-aeson
    - text
    - http-types
    - aeson
    - vector
    - unordered-containers
    - scientific
    - time
    - stm
    - bytestring
    - tagged
    when:
    - condition: flag(lib-werror)
      ghc-options:
      - -Wall
      - -Werror

benchmarks:
  katip-elasticsearch-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options: -O
    dependencies:
    - base
    - katip
    - katip-elasticsearch
    - aeson
    - bloodhound
    - criterion >=1.1.0.0
    - deepseq
    - http-client
    - rng-utils
    - text
    - time
    - unagi-chan
    - unordered-containers
    - uuid

executables:
  example: &my-exe
    source-dirs: examples
    main: example.hs
    dependencies:
      - base
      - bloodhound
      - http-client
      - katip
      - katip-elasticsearch
    ghc-options: -O -threaded -prof
  bulk-example:
    <<: *my-exe
    main: bulk-example.hs

flags:
  lib-werror:
    description: null
    manual: true
    default: false
